### ISSUE TITLE
ENORESTARGET "URL sources can't resolve targets" when installing from URLs with user information

### ISSUE THREAD

**Issue by ankon** [bower/bower#2391]
**Output of `bower -v && npm -v && node -v`:**

```
1.8.0
3.10.9
v7.1.0
```

**Additional environment details (proxy, private registry, etc.):**

We use `bower install -s` in our travis steps to install some content from a private repository even for open source builds. See https://github.com/bower/bower/issues/2176 for some more details about this.

**Steps to reproduce the issue:**

1. bower install -s https://${GH_TOKEN}@github.com/Collaborne/collaborne-build-tools.git

GH_TOKEN is an environment variable containing a GitHub token for repository access.

**Describe the results you received:**

```
bower                     ENORESTARGET URL sources can't resolve targets
```

**Describe the results you expected:**

(bower installing the requested item)

**Additional information:**

* This used to work in pre-1.8.0 bower.
* The problem is the '@' character in the URL: Due to other means of authentication, this works my development machine: `bower install -s https://github.com/Collaborne/collaborne-build-tools.git`. 
* #2272 might be related (this was closed because one must not specify a version in the URL - but note how the '@' in their URLs is part of the path.)

**Comment by ankon** [comment]
https://github.com/bower/bower/pull/2322 looks like the cause of this.

**Comment by wookoouk** [comment]
Yep, it looks like is was caused by #2322, I'll put a fix in today.

**Comment by ankon** [comment]
For reference: #2395 is the PR that should fix this.

**Comment by srvance** [comment]
I'm still seeing this in bower 1.8.0. It's preventing me from referencing a development branch version of a package.

**Comment by ankon** [comment]
> I'm still seeing this in bower 1.8.0

This was introduced in bower 1.8.0, so yes, you'd be seeing it there. If you can: use bower 1.7.9 to avoid the problem.

**Comment by srvance** [comment]
I reverted to 1.7.9 and had the same problem. (Uninstalled globally, installed 1.7.9 globally, added 1.7.9 to my local project. The only thing I couldn't do was change ember-cli's dependency on 1.8.0, which may have been why it persisted.)

**Comment by justin-c-rounds** [comment]
Is there a workaround for this? I'm currently having this same problem.

**Comment by robertology** [comment]
I saw the problem with bower 1.8 but is working as expected in 1.8.2
