### ISSUE TITLE
BROKEN CHANGE!! 1.8.8 to 1.8.10 

### ISSUE THREAD

**Issue by javasgl** [bower/bower#2590]
**Output of `bower -v && npm -v && node -v`:**

```
1.8.10
3.10.10
v6.12.0
```

**Additional environment details (proxy, private registry, etc.):**
```
warning bower > github@14.0.0: 'github' has been renamed to '@octokit/rest' (https://git.io/vNB11)
warning bower > opn@6.0.0: The package has been renamed to `open`
warning bower > bower-registry-client > mkdirp@0.3.5: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
warning bower > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning bower > bower-registry-client > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning bower > request > har-validator@5.1.5: this library is no longer supported
warning gulp.spritesmith > gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
[2/4] 🚚  Fetching packages...
error configstore@5.0.1: The engine "node" is incompatible with this module. Expected version ">=8". Got "6.12.0"
error Found incompatible module.
```
in bower version 1.8.8, lru-cache is 2.7.3

but in bower version 1.8.10, lru-cache has been upgrade to 6.0

**Comment by yanxiaosong0902** [comment]
in bower v1.8.10
run yarn install:
[1/4] 🔍  Resolving packages...
warning bower > github@14.0.0: 'github' has been renamed to '@octokit/rest' (https://git.io/vNB11)
warning bower > bower-registry-client > mkdirp@0.3.5: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
warning bower > opn@6.0.0: The package has been renamed to `open`
warning bower > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning bower > bower-registry-client > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning bower > request > har-validator@5.1.5: this library is no longer supported
[2/4] 🚚  Fetching packages...
error lru-cache@6.0.0: The engine "node" is incompatible with this module. Expected version ">=10". Got "8.12.0"
error Found incompatible module.

**Comment by sheerun** [comment]
Thank you for notice, no need for exclamation marks. I'll try to fix it

**Comment by sheerun** [comment]
Bower 1.8.11 should fix this

**Comment by krazyjakee** [comment]
Looks like there is still some issue with the github resolver that is still present in 1.8.11. I'd argue at least one of those exclamation marks was warranted.

```
Error: Cannot find module 'qs'
Require stack:
- /Users/User/.nvm/versions/node/v14.12.0/lib/node_modules/bower/lib/node_modules/request/lib/querystring.js
- /Users/User/.nvm/versions/node/v14.12.0/lib/node_modules/bower/lib/node_modules/request/request.js
- /Users/User/.nvm/versions/node/v14.12.0/lib/node_modules/bower/lib/node_modules/request/index.js
- /Users/User/.nvm/versions/node/v14.12.0/lib/node_modules/bower/lib/util/download.js
- /Users/User/.nvm/versions/node/v14.12.0/lib/node_modules/bower/lib/core/resolvers/GitHubResolver.js
- /Users/User/.nvm/versions/node/v14.12.0/lib/node_modules/bower/lib/core/resolvers/index.js
- /Users/User/.nvm/versions/node/v14.12.0/lib/node_modules/bower/lib/core/resolverFactory.js
- /Users/User/.nvm/versions/node/v14.12.0/lib/node_modules/bower/lib/core/PackageRepository.js
- /Users/User/.nvm/versions/node/v14.12.0/lib/node_modules/bower/lib/core/Manager.js
- /Users/User/.nvm/versions/node/v14.12.0/lib/node_modules/bower/lib/core/Project.js
- /Users/User/.nvm/versions/node/v14.12.0/lib/node_modules/bower/lib/commands/install.js
- /Users/User/.nvm/versions/node/v14.12.0/lib/node_modules/bower/lib/commands/index.js
- /Users/User/.nvm/versions/node/v14.12.0/lib/node_modules/bower/lib/index.js
- /Users/User/.nvm/versions/node/v14.12.0/lib/node_modules/bower/lib/bin/bower.js
- /Users/User/.nvm/versions/node/v14.12.0/lib/node_modules/bower/bin/bower
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:893:15)
    at Function.Module._load (internal/modules/cjs/loader.js:743:27)
    at Module.require (internal/modules/cjs/loader.js:965:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/User/.nvm/versions/node/v14.12.0/lib/node_modules/bower/lib/node_modules/request/lib/querystring.js:3:10)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14)
    at Module.require (internal/modules/cjs/loader.js:965:19) {
  code: 'MODULE_NOT_FOUND'
}
```
