### ISSUE TITLE
Problem installing plugins with bower

### ISSUE THREAD

**Issue by Anderson-Juhasc** [bower/bower#720]
I have the following problem which any command to run the bower.

$ bower search jquery
bower EACCES        EACCES, open '/home/andersonjuhasc/.cache/bower/registry/bower.herokuapp.com/search/jquery'

Stack trace:
Error: EACCES, open '/home/andersonjuhasc/.cache/bower/registry/bower.herokuapp.com/search/jquery'

Console trace:
Trace
    at StandardRenderer.error (/usr/lib/node_modules/bower/lib/renderers/StandardRenderer.js:71:17)
    at Logger.updateNotifier.packageName (/usr/lib/node_modules/bower/bin/bower:113:18)
    at Logger.EventEmitter.emit (events.js:95:17)
    at Logger.emit (/usr/lib/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/lib/node_modules/bower/lib/commands/search.js:31:16
    at _rejected (/usr/lib/node_modules/bower/node_modules/q/q.js:713:24)
    at /usr/lib/node_modules/bower/node_modules/q/q.js:739:30
    at Promise.when (/usr/lib/node_modules/bower/node_modules/q/q.js:979:31)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/bower/node_modules/q/q.js:661:41)
    at /usr/lib/node_modules/bower/node_modules/q/q.js:543:44

System info:
Bower version: 1.1.0
Node version: 0.10.13
OS: Linux 3.2.0-49-generic-pae ia32

**Comment by osalama7** [comment]
fixed it using bower cache clean, and running chown -R /pathtofolder on restricted paths

**Comment by oshliaer** [comment]
I've fixed it like @osalama7 using `bower cache clean`, and running `chown -R myuser /restricted_path`.

My npm permissions resolve option is to [change npm's default directory to another directory](https://docs.npmjs.com/getting-started/fixing-npm-permissions).

**Comment by whitmanc** [comment]
:+1: for `bower cache clean && chown -R myuser /restricted_path`

**Comment by modusss** [comment]
I have the same error with ubuntu 16.

It wasn't resolved yet

**Comment by Karthickbg** [comment]
sudo chmod -R 777  /home/{user}/.cache/bower/

**Comment by rhanys** [comment]
I resolving the same error on ElementaryOS Loki by running this:
`sudo rm -rf /home/{user}/.cache/bower/`
`bower install`
